Rebecca SteelHall.MAUI
Dlubal-Software/Dlubal_CSharp_Client pull request #37
Opened 2023-06-28 18:12 UTC by Rebecca-Coding21

# Description

I implemented an example program for C# WebService using .NET MAUI. The example program creates a steel hall in RFEM. The user define values for frame height, frame span, frame distance, frame number and rood angle. Otherwise default values are used for calculation. The buttons give the ability to start the calculation, export the results as csv-file, close the current model or close the application.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Attached examples
- [x] Own example attached to Pull Request

* RFEM version: 6.02.0070
* .Net SDK: .NET 7.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-12 13:32 UTC, jarabroz reviewed
We can define target platform just for Windows.

2023-07-12 13:56 UTC, jarabroz requested changes
Define only build for Win platform as active

2023-07-12 13:56 UTC, jarabroz commented on examples/SteelHall.MAUI/SteelHall - Backup.MAUI.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
File not needed

2023-07-12 13:56 UTC, jarabroz commented on examples/SteelHall.MAUI/App.xaml.cs
> +            //            var width = (int)MainPage.WidthRequest;
If not necessary remove commented code

2023-07-12 14:03 UTC, jarabroz requested changes
Finished review. Just make na WIN app

2023-07-13 08:50 UTC, Rebecca-Coding21 commented on examples/SteelHall.MAUI/SteelHall - Backup.MAUI.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Done.

2023-07-13 08:50 UTC, Rebecca-Coding21 commented on examples/SteelHall.MAUI/App.xaml.cs
> +            //            var width = (int)MainPage.WidthRequest;
Done.

2023-09-08 06:26 UTC, jarabroz approved these changes

2023-09-08 06:29 UTC, merged